name: Build and deploy on Azure container apps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    # paths:
    # - 'webui/**' 
  pull_request_target:
    branches: 
      [ main ]
  # Allow mannually trigger 
  workflow_dispatch:   


permissions:
  id-token: write #This is required for requesting the OIDC JWT Token
  contents: read #Required when GH token is used to authenticate with private repo

   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.PLATTENTESTS_REGISTRY_USERNAME }}
          password: ${{ secrets.PLATTENTESTS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jetzlstorfer/plattentests-web:${{ github.sha }}
          file: ./webui/Dockerfile
          build-args: GIT_SHA=${{ github.sha }}
          context: .


  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PLATTENTESTS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PLATTENTESTS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PLATTENTESTS_AZURE_SUBSCRIPTION_ID }}


      - name: Deploy to containerapp
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n plattentests -g aca-plattentests --server docker.io --username  ${{ secrets.PLATTENTESTS_REGISTRY_USERNAME }} --password ${{ secrets.PLATTENTESTS_REGISTRY_PASSWORD }}
            az containerapp update -n plattentests -g aca-plattentests --image jetzlstorfer/plattentests-web:${{ github.sha }}
