name: Build and deploy to Azure function

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Update go modules
      run: go mod tidy

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -v -o myapp .

    - name: Test
      run: go test -v ./...

    - name: Zip the build output
      run: zip -r myapp.zip ./myapp

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: plattentests-go
        path: myapp.zip

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    steps:
    - uses: actions/checkout@v4
    - name: Download
      uses: actions/download-artifact@v4
      with:
        name: plattentests-go
        path: ./myapp.zip
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.PLATTENTESTS_FUNC_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.PLATTENTESTS_FUNC_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.PLATTENTESTS_FUNC_AZURE_SUBSCRIPTION_ID }}
    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: plattentests-go
        package: myapp.zip